export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

export const CONNECTED_WITH_SERVER = 'CONNECTED_WITH_SERVER';
export const TRYING_CONNECTION_WITH_SEVER = 'TRYING_CONNECTION_WITH_SEVER';
