export const jobTitleChoices = {
    'Machine Operator / Helper': 'Machine Operator / Helper',
    'IT / ITeS': 'IT / ITeS',
    'Driver (Private Vehicles)': 'Driver (Private Vehicles)',
    'Driver (Commercial Vehicles)': 'Driver (Commercial Vehicles)',
    'Driver (Heavy Vehicles - Bus, Truck, Trailer, etc.)': 'Driver (Heavy Vehicles - Bus, Truck, Trailer, etc.)',
    'Backhoe Loader Operator': 'Backhoe Loader Operator',
    'Tractor Operator': 'Tractor Operator',
    'Security Staff': 'Security Staff',
    'Bouncer': 'Bouncer',
    'Security Guard (Armed)': 'Security Guard (Armed)',
    'PSO (Personal Security Officer)': 'PSO (Personal Security Officer)',
    'Computer Operator': 'Computer Operator',
    'Data Entry Operator': 'Data Entry Operator',
    'Plumber': 'Plumber',
    'Electrician': 'Electrician',
    'Housekeeping Staff': 'Housekeeping Staff',
    'Retail Sales Staff': 'Retail Sales Staff',
    'Retail Store Keeper': 'Retail Store Keeper',
    'Cashier': 'Cashier',
    'Sales Manager': 'Sales Manager',
    'Field Officer': 'Field Officer',
    'Supervisor': 'Supervisor',
    'Beautician': 'Beautician',
    'BPO / Call Centre': 'BPO / Call Centre',
    'Receptionist': 'Receptionist',
    'Management / Admin': 'Management / Admin',
    'HR': 'HR',
    'Accounts Executive': 'Accounts Executive',
    'GST Executive': 'GST Executive',
    'ESIC / PF Executive': 'ESIC / PF Executive',
    'Cook': 'Cook',
    'Tailor': 'Tailor',
    'Delivery Jobs': 'Delivery Jobs',
    'Carpenter': 'Carpenter',
    'Painter': 'Painter',
    'Mason': 'Mason',
    'Construction Worker': 'Construction Worker',
    'Bar Binder': 'Bar Binder',
    'Welder': 'Welder',
    'CNC machine operator': 'CNC machine operator',
    'Fitter': 'Fitter',
    'Domestic Help / Maid /  Home-cleaning': 'Domestic Help / Maid /  Home-cleaning',
    'Rider': 'Rider',
    'AC Repairing / AC Service': 'AC Repairing / AC Service',
    'Electronics Repair': 'Electronics Repair',
    'Home Appliances Repair': 'Home Appliances Repair',
    'Waiter (Restaurant)': 'Waiter (Restaurant)',
    'Bartender': 'Bartender',
    'Hair Dresser (Male)': 'Hair Dresser (Male)',
    'Hair Dresser (Female)': 'Hair Dresser (Female)',
    'Personal Assistant': 'Personal Assistant',
    'Peon': 'Peon',
    'DG Operator': 'DG Operator',
    'STP Operator': 'STP Operator',
    'WTP Operator': 'WTP Operator',
    'Lift  Operator': 'Lift  Operator',
    'Lift Technician': 'Lift Technician',
    'Water Tank Cleaner': 'Water Tank Cleaner',
    'Car Washer / Cleaner': 'Car Washer / Cleaner',
    'Web Designer': 'Web Designer',
    'Web Developer': 'Web Developer',
    'Graphic Designer': 'Graphic Designer',
    'Fitness Trainer': 'Fitness Trainer',
    'Yoga Trainer': 'Yoga Trainer',
    'Logistics Staff (Loading / Unloading )': 'Logistics Staff (Loading / Unloading )',
    'Packaging Staff': 'Packaging Staff',
    'Warehouse Staff': 'Warehouse Staff',
    'Nursing Staff': 'Nursing Staff',
    'Patient Care': 'Patient Care',
    'Baby Sitter / Nanny / Mother Care': 'Baby Sitter / Nanny / Mother Care',
    'Parking Management Staff': 'Parking Management Staff',
    'MST (Multi Tasking Staff)': 'MST (Multi Tasking Staff)',
    'Housekeeping Supervisor': 'Housekeeping Supervisor',
    'Security Supervisor': 'Security Supervisor',
    'Training Supervisor': 'Training Supervisor',
    'Landscaping supervisor': 'Landscaping supervisor',
    'Plumbing Supervisor': 'Plumbing Supervisor',
    'Manpower Mobiliser': 'Manpower Mobiliser',
    'Leather Worker': 'Leather Worker',
    'Dairy Worker': 'Dairy Worker',
    'Facade Cleaner': 'Facade Cleaner',
    'Band-Baaja Staff': 'Band-Baaja Staff',
    'Party Singers': 'Party Singers',
    'Other': 'Other'
};

export const stateChoices = {
    'Andhra Pradesh': 'Andhra Pradesh',
    'Arunachal Pradesh ': 'Arunachal Pradesh ',
    'Assam': 'Assam',
    'Bihar': 'Bihar',
    'Chhattisgarh': 'Chhattisgarh',
    'Goa': 'Goa',
    'Gujarat': 'Gujarat',
    'Haryana': 'Haryana',
    'Himachal Pradesh': 'Himachal Pradesh',
    'Jammu and Kashmir ': 'Jammu and Kashmir ',
    'Jharkhand': 'Jharkhand',
    'Karnataka': 'Karnataka',
    'Kerala': 'Kerala',
    'Madhya Pradesh': 'Madhya Pradesh',
    'Maharashtra': 'Maharashtra',
    'Manipur': 'Manipur',
    'Meghalaya': 'Meghalaya',
    'Mizoram': 'Mizoram',
    'Nagaland': 'Nagaland',
    'Odisha': 'Odisha',
    'Punjab': 'Punjab',
    'Rajasthan': 'Rajasthan',
    'Sikkim': 'Sikkim',
    'Tamil Nadu': 'Tamil Nadu',
    'Telangana': 'Telangana',
    'Tripura': 'Tripura',
    'Uttar Pradesh': 'Uttar Pradesh',
    'Uttarakhand': 'Uttarakhand',
    'West Bengal': 'West Bengal',
    'Andaman and Nicobar Islands': 'Andaman and Nicobar Islands',
    'Chandigarh': 'Chandigarh',
    'Dadra and Nagar Haveli': 'Dadra and Nagar Haveli',
    'Daman and Diu': 'Daman and Diu',
    'Lakshadweep': 'Lakshadweep',
    'National Capital Territory of Delhi': 'Delhi and Delhi NCR',
    'Puducherry': 'Puducherry',
};

export const educationalQualificationChoices = {
    'BELOW 5th Class': 'BELOW 5th Class',
    'Class 5th to 9th': 'Class 5th to 9th',
    '10th pass': '10th pass',
    '12th pass': '12th pass',
    'ITI': 'ITI',
    'Polytechnic': 'Polytechnic',
    'Diploma': 'Diploma',
    'Graduate (B.Sc., B.A., B.Com.)': 'Graduate (B.Sc., B.A., B.Com.)',
    'Other Graduate (Any Stream)': 'Other Graduate (Any Stream)',
    'B.Tech. (Any Stream)': 'B.Tech. (Any Stream)',
    'M.Tech. (Any Stream)': 'M.Tech. (Any Stream)',
    'Post graduate (Any stream)': 'Post graduate (Any stream)',
    'MBA/PGDM (Any Stream)': 'MBA/PGDM (Any Stream)'
};
